name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel for unicorn
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/TianXiao203/android_kernel_xiaomi_sm8450
          kernel-branch: lineage-23.2
          config: vendor/unicorn_GKI.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          android-version: 12
          disable-lto: true
          lxc: true
          lxc-patch: true
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
